Exception ignored in: <function AstRef.__del__ at 0x7153457f4af0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/z3/z3.py", line 352, in __del__
    Z3_dec_ref(self.ctx.ref(), self.as_ast())
  File "/usr/local/lib/python3.10/site-packages/z3/z3core.py", line 1626, in Z3_dec_ref
    _elems.f(a0, a1)
KeyboardInterrupt: 
mythril.mythril.mythril_analyzer [CRITICAL]: Keyboard Interrupt
The analysis was completed successfully. No issues were detected.


got 3 SIGTERM/SIGINTs, forcefully exiting
